CREATE TABLE orders (
    id VARCHAR(36) NOT NULL,
    shift_id VARCHAR(36) NOT NULL,
    cashier_id VARCHAR(36) NOT NULL,
    table_id VARCHAR(36) NULL,
    promo_id VARCHAR(36) NULL,
    status ENUM('draft','pending_payment','paid','cancelled') NOT NULL DEFAULT 'draft',
    subtotal BIGINT NOT NULL DEFAULT 0,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (shift_id) REFERENCES shifts(id),
    FOREIGN KEY (cashier_id) REFERENCES users(id),
    FOREIGN KEY (table_id) REFERENCES tables(id),
    FOREIGN KEY (promo_id) REFERENCES promos(id),
    INDEX idx_orders_shift_id (shift_id),
    INDEX idx_orders_cashier_id (cashier_id),
    INDEX idx_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
